rust: 1.87.0 -> 1.89.0

diff --git a/rust/Pkgfile b/rust/Pkgfile
--- a/rust/Pkgfile
+++ b/rust/Pkgfile
@@ -1,13 +1,13 @@
 # Description: The Rust language with Cargo included.
 # URL: https://www.rust-lang.org/
 # Maintainer: CRUX System Team, core-ports at crux dot nu
-# Depends on: compiler-rt
-# Optional: clang libgit2 lld polly sccache
+# Depends on: compiler-rt lld
+# Optional: libgit2 lld polly sccache
 
 name=rust
-version=1.87.0
-_date=2025-04-03
-_rustc=1.86.0
+version=1.89.0
+_date=2025-06-26
+_rustc=1.88.0
 _cargo=$_rustc
 release=1
 
@@ -18,7 +18,8 @@ source=(https://static.rust-lang.org/dist/${name}c-$version-src.tar.xz
     0001-bootstrap-Change-libexec-dir.patch
     0002-bootstrap-Change-bash-completion-dir.patch
     0003-compiler-Change-LLVM-targets.patch
-    0004-compiler-Use-wasm-ld-for-wasm-targets.patch)
+    0004-compiler-Use-wasm-ld-for-wasm-targets.patch
+    riscv64-disable-f16-f128.patch)
 
 unpack_source() {
     for file in ${source[@]}; do
@@ -67,10 +68,11 @@ build() {
     patch -p1 -i $SRC/0002-bootstrap-Change-bash-completion-dir.patch
     patch -p1 -i $SRC/0003-compiler-Change-LLVM-targets.patch
     patch -p1 -i $SRC/0004-compiler-Use-wasm-ld-for-wasm-targets.patch
+    patch -p1 -i $SRC/riscv64-disable-f16-f128.patch
 
 cat <<- EOF > $SRC/bootstrap.toml
 profile = "dist"
-change-id = 138986
+change-id = 142379
 
 [llvm]
 ninja = true
@@ -92,7 +94,7 @@ debuginfo-level = 1
 debuginfo-level-std = 2
 codegen-tests = false
 backtrace-on-ice = true
-jemalloc = true
+jemalloc = false
 remap-debuginfo = false
 debug-assertions = false
 
@@ -102,10 +104,12 @@ deny-warnings = false
 optimize = true
 codegen-backends = ["llvm"]
 lld = false
+use-lld = false
+lto = "off"
 
 [build]
 target = ["riscv64gc-unknown-linux-gnu"]
-description = "CRUX"
+description = "CRUX RISCV-64"
 tools = ["cargo",
   "clippy",
   "rustfmt",
@@ -123,9 +127,6 @@ vendor = true
 locked-deps = true
 python = "/usr/bin/python3"
 optimized-compiler-builtins = true
-@CARGO@
-@RUST@
-@RUSTFMT@
 
 [target.riscv64gc-unknown-linux-gnu]
 llvm-config = "/usr/bin/llvm-config"
@@ -134,29 +135,27 @@ cc = "/usr/bin/gcc"
 cxx = "/usr/bin/g++"
 ar = "/usr/bin/gcc-ar"
 ranlib = "/usr/bin/gcc-ranlib"
-linker = "/usr/bin/gcc"
 EOF
 
-    if [ -e '/usr/bin/rustc' ]; then
-        if ! /usr/bin/ldd /usr/bin/rustc /usr/bin/cargo | grep -q -E '.*not found'; then
-            sed    -e 's|@CARGO@|cargo = "/usr/bin/cargo"|' \
-                -e 's|@RUST@|rustc = "/usr/bin/rustc"|' \
-                -e 's|@RUSTFMT@|rustfmt = "/usr/bin/rustfmt"|' \
-                -i $SRC/bootstrap.toml
-        else
-            sed -e 's|@CARGO@||' -e 's|@RUST@||' -e 's|@RUSTFMT@||' -i $SRC/bootstrap.toml
-            printf "\e[031mShared library missing, not using system rust to bootstrap.\033[0m\n"
-        fi
-    else
-        sed -e 's|@CARGO@||' -e 's|@RUST@||' -e 's|@RUSTFMT@||' -i $SRC/bootstrap.toml
-    fi
-
-    if prt-get isinst clang lld; then
-        sed -e 's|@TARGETCC@|"clang"|g' -e 's|@TARGETCXX@|"clang++"|g' -e 's|@TARGETAR@|"llvm-ar"|g' -e 's|@TARGETRANLIB@|"llvm-ranlib"|g' -i $SRC/bootstrap.toml
-    else
-        sed -e 's|@TARGETCC@|"gcc"|g' -e 's|@TARGETCXX@|"g++"|g' -e 's|@TARGETAR@|"gcc-ar"|g' -e 's|@TARGETRANLIB@|"gcc-ranlib"|g' -i $SRC/bootstrap.toml
-    fi
-    prt-get isinst lld && sed -e 's|@LLD@|use-lld = true\nlld = true|' -i $SRC/bootstrap.toml || sed -e 's|@LLD@||' -i $SRC/bootstrap.toml
+#    if [ -e '/usr/bin/rustc' ]; then
+#        if ! /usr/bin/ldd /usr/bin/rustc /usr/bin/cargo | grep -q -E '.*not found'; then
+#            sed    -e 's|@CARGO@|cargo = "/usr/bin/cargo"|' \
+#                -e 's|@RUST@|rustc = "/usr/bin/rustc"|' \
+#                -e 's|@RUSTFMT@|rustfmt = "/usr/bin/rustfmt"|' \
+#                -i $SRC/bootstrap.toml
+#        else
+#            sed -e 's|@CARGO@||' -e 's|@RUST@||' -e 's|@RUSTFMT@||' -i $SRC/bootstrap.toml
+#            printf "\e[031mShared library missing, not using system rust to bootstrap.\033[0m\n"
+#        fi
+#    else
+#        sed -e 's|@CARGO@||' -e 's|@RUST@||' -e 's|@RUSTFMT@||' -i $SRC/bootstrap.toml
+#    fi
+#
+#    if prt-get isinst clang lld; then
+#        sed -e 's|@TARGETCC@|"clang"|g' -e 's|@TARGETCXX@|"clang++"|g' -e 's|@TARGETAR@|"llvm-ar"|g' -e 's|@TARGETRANLIB@|"llvm-ranlib"|g' -i $SRC/bootstrap.toml
+#    else
+#        sed -e 's|@TARGETCC@|"gcc"|g' -e 's|@TARGETCXX@|"g++"|g' -e 's|@TARGETAR@|"gcc-ar"|g' -e 's|@TARGETRANLIB@|"gcc-ranlib"|g' -i $SRC/bootstrap.toml
+#    fi
     prt-get isinst polly && sed -e 's|@POLLY@|polly = true|' -i $SRC/bootstrap.toml || sed -e 's|@POLLY@||' -i $SRC/bootstrap.toml
 
     cat $SRC/bootstrap.toml
@@ -174,20 +173,19 @@ EOF
     #   --> src/bootstrap/lib.rs:280:5
     #   = note: `-D dead-code` implied by `-D warnings`
     export RUSTFLAGS+=' -A dead_code'
+    export RUSTFLAGS+=' -C link-arg=-fuse-ld=bfd'
 
     unset CFLAGS CXXFLAGS
 
     { [ ! -e /usr/include/libssh2.h ] ||
         export LIBSSH2_SYS_USE_PKG_CONFIG=1; }
     export RUST_BACKTRACE=full
+    LIBGCC_DIR="$(dirname "$(gcc -print-libgcc-file-name)")"
     /usr/bin/python3 ./x.py build --config="${SRC}"/bootstrap.toml -j ${JOBS-1}
     DESTDIR=$PKG /usr/bin/python3 ./x.py --config="${SRC}"/bootstrap.toml install
 
     prt-get isinst bash-completion || rm -r $PKG/usr/share/bash-completion
     prt-get isinst zsh || rm -r $PKG/usr/share/zsh
-
-    install -d $PKG/etc/revdep.d
-    echo "/usr/lib/rustlib/i686-unknown-linux-gnu/lib" > $PKG/etc/revdep.d/$name
 
     # cleanup
     rm -r $PKG/usr/share/doc
